name: Auto Assign to Projects based on software/hardware label

on:
  issues:
    types: [labeled]
  pull_request:
    types: [labeled]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to projects based on label
    steps:
    - name: Assign issues and pull requests with `hardware` label to project `Hardware`
      uses: srggrs/assign-one-project-github-action@1.2.0
      if: |
        contains(github.event.issue.labels.*.name, 'hardware') ||
        contains(github.event.pull_request.labels.*.name, 'hardware')
      with:
        project: 'https://github.com/PlanktonPlanet/PlanktonScope/projects/2'
        column_name: 'Bugs'

    - name: Assign issues and pull requests with `software` label to project `Sofware`
      uses: srggrs/assign-one-project-github-action@1.2.0
      if: |
        contains(github.event.issue.labels.*.name, 'bug') ||
        contains(github.event.pull_request.labels.*.name, 'bug')
      with:
        project: 'https://github.com/PlanktonPlanet/PlanktonScope/projects/1'
        column_name: 'To Do'
