---
name: release-channel-documentation/stable
on:
  push:
    tags:
      - 'documentation/v[0-9]+.[0-9]+.[0-9]+'

jobs:
  ff-branch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          # Needed to be able to push to protected (push-restricted) branches:
          ssh-key: ${{secrets.RELEASE_BRANCH_DEPLOY_KEY}}
          persist-credentials: true

      - run: |
          git checkout documentation/stable
          git merge --ff-only ${{ github.ref_name }}

      - uses: ad-m/github-push-action@v1.0.0
        with:
          branch: documentation/stable
          ssh: true

  deploy-docs-site:
    # We call this workflow manually because it doesn't appear to be triggered automatically by a
    # push of the documentation/stable branch from the ff-branch job:
    uses: ./.github/workflows/documentation-deploy-stable.yml
    needs: ff-branch
    secrets: inherit
